:compat-mode:
= Flyway

== Introdução
Ilustra uso combinado de Flyway, H2 e Spring.

== Importante
Configure o driver do H2 a ser empregado pelo seu IDE usando a versão
correta. O que isso significa? Significa usar a versão que também
´e empregada pelo Spring e pelo Flyway.

O arquivo _pom.xml_ faz uso do **spring-boot-starter-parent** e,
nesse caso, a versão utilizada é indicada pela propriedade
 _h2.version_. No Intellij basta clicar no pom com o botão direito,
 Maven e, por fim, Show Effective Pom. Isso mostrará a versão
 empregada pelo Spring Boot.

 A versão empregada pelo Flyway é especificada no próprio _pom.xml_ e,
 portanto, basta usar a propriedade _h2.version_ (conforme feito).

 Observe que essa também deve ser a versão empregada para iniciar
 o servidor, conforme a configuração do **exec-maven-plugin**.

== Iniciar o H2 (Server Mode)
Basta executar ```mvn exec:java```.

== Passos

```
$ mvn clean package
$ java -jar target/spring-flyway-1.0.0.jar
```

== Explanação
Ilustra como uma coluna pode ser adicionada ao banco de dados.

O diretório `src/main/db/migration` contém detalhes da migração.
